apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled
spec:
  minReplicaCount: 1            
  maxReplicaCount: 1 
  activeDeadlineSeconds: 1800
  backoffLimit: 2
  # Run every minute
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: scheduled
            image: container-app-jobs-examples-scheduled:latest
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure