apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: event-driven
  namespace: default
spec:
  minReplicaCount: 1            
  maxReplicaCount: 1 
  activeDeadlineSeconds: 1800
  backoffLimit: 2
  jobTargetRef:
    template:
      spec:
        containers:
        - name: event-driven
          env:
          - name: AZURE_STORAGE_CONNECTION_STRING
            value: "<YOUR_STORAGE_CONNECTION_STRING"
          image: container-app-job-examples-event-driven:latest
          imagePullPolicy: IfNotPresent
        restartPolicy: Never
  triggers:
  - type: azure-blob
    metadata:
      blobContainerName: yourStorageContainerName
      blobCount: '5'
      connectionFromEnv: AZURE_STORAGE_CONNECTION_STRING
      accountName: yourStorageAccountName